### ISSUE TITLE
`HEAD` builds fail from plt.eecs.northwestern.edu

### ISSUE THREAD

**Issue by mbutterick** [greghendershott/travis-racket#11]
More of a question than an issue: is there a special reason we should use `plt.eecs.northwestern.edu` as the host for `HEAD` builds? Because over the last few months, I’ve had increasing problems with that server (probably 25–30% of my `HEAD` builds (of multiple packages) fail due to network timeouts, [for instance](https://travis-ci.org/mbutterick/pollen/jobs/95408174)).

**Comment by greghendershott** [comment]
It's a great question. I wish I knew the answer.

I changed it back in January on commit ebbc14e, from Utah to Northwestern, because Utah was unreliable at the time for me. IIRC @samth advised on IRC that Northwestern would be better. It seemed to be, back then. Perhaps not anymore. If I could ask a favor, could you please ping someone on the Racket team to ask what server if any is preferable, these days?  I'm happy to change.

Although your example link shows the HEAD job succeeding, I'm guessing that's only eventually -- only because you reset the job until it succeeded?

**Comment by mbutterick** [comment]
> only because you reset the job until it succeeded?

Right. What I didn’t know is if the Utah server was fair game, and it is, so I switched, and we'll see what happens. Probably best to assume that performance may occasionally be erratic (Netflix + YouTube = 80% of academic network utilization?). I'll think about how the install script might have a simple failover heuristic.

**Comment by samth** [comment]
Neither is preferred over the other. Either one may have failures, and thus failover is a good idea. There's also the issue that Travis occasionally has problems downloading things from either site, for reasons I haven't understood.
