### ISSUE TITLE
Moved to https at Northwestern causes curl problems

### ISSUE THREAD

**Issue by dvanhorn** [greghendershott/travis-racket#13]
This URL has permanently moved:

http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh

to:

https://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh

When curl fetches it, it fails with a certificate error.

For example: https://s3.amazonaws.com/archive.travis-ci.org/jobs/114850694/log.txt

**Comment by greghendershott** [comment]
install-racket.sh uses `curl -L` to follow redirects, which AFAIK is good to do.

When I try `curl -L -o ./racket.sh
http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh`,
now it works.

With `curl -i -H` I can see that it does have a 301 redirect. It looks
like they had a certificate error that they fixed?

As it's a 301 Permanent redirect, we could update install-racket.sh to
use the new https URL in the first place. I'll consider that the
action item on this issue, unless you feel otherwise?

I'd be happy to take PR for this change if someone wants to do it
before I can get to it.

**Comment by dvanhorn** [comment]
It looks like the certificate error was fixed, which resolved this issue.  Thanks.
